[firefox*]
# capslock = overload(control, macro(escape))
ctrl_layer.s = C-A-s
ctrl_layer.t = C-A-t
meta_layer.s = C-s
meta_layer.t = C-t
# control.t = C-S-u
# control.a = macro(home)
# control.e = macro(end)
# # alt.a = C-a
#
# control.f = macro(right)
# control.b = macro(left)
# control.n = macro(down)
# control.p = macro(up)
#
# [kitty]
# capslock = overload(control, macro(escape))
# control.a = C-a
# control.e = C-e
#
#
