source "/Users/mei/.local/share/sheldon/repos/github.com/romkatv/zsh-defer/zsh-defer.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/mafredri/zsh-async/async.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/jeffreytse/zsh-vi-mode/zsh-vi-mode.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/romkatv/powerlevel10k/powerlevel10k.zsh-theme"
source "/Users/mei/.local/share/sheldon/repos/github.com/larkery/zsh-histdb/zsh-histdb.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/zsh-users/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/BurntSushi/ripgrep/crates/core/flags/complete/rg.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/Aloxaf/fzf-tab/fzf-tab.plugin.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/zdharma-continuum/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/dim-an/cod/cod.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/mroth/evalcache/evalcache.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/momo-lab/zsh-abbrev-alias/abbrev-alias.plugin.zsh"
