source "/Users/mei/.local/share/sheldon/repos/github.com/romkatv/zsh-defer/zsh-defer.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/mroth/evalcache/evalcache.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/mafredri/zsh-async/async.plugin.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/jeffreytse/zsh-vi-mode/zsh-vi-mode.plugin.zsh"
source "/Users/mei/.local/share/sheldon/repos/github.com/romkatv/powerlevel10k/powerlevel10k.zsh-theme"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/zsh-users/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/BurntSushi/ripgrep/crates/core/flags/complete/rg.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/junegunn/fzf/shell/completion.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/junegunn/fzf/shell/key-bindings.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/Aloxaf/fzf-tab/fzf-tab.plugin.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/zdharma-continuum/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/dim-an/cod/cod.plugin.zsh"
export PER_DIRECTORY_HISTORY_TOGGLE=^V
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/jimhester/per-directory-history/per-directory-history.plugin.zsh"
export PER_DIRECTORY_HISTORY_TOGGLE=^V
source "/Users/mei/.local/share/sheldon/repos/github.com/momo-lab/zsh-abbrev-alias/abbrev-alias.plugin.zsh"
zsh-defer source "/Users/mei/.local/share/sheldon/repos/github.com/sunlei/zsh-ssh/zsh-ssh.plugin.zsh"
