# [desktop/wm/keybindings]
# switch-applications=['<Alt>j']
# switch-applications-backward=['<Alt>k']
# switch-windows=['<Alt>l']
# switch-windows-backward=['<Alt>h']
# move-to-workspace-left=['<Shift><Alt>h']
# move-to-workspace-down=['<Shift><Alt>j']
# move-to-workspace-up=['<Shift><Alt>k']
# move-to-workspace-right=['<Shift><Alt>l']
# switch-to-workspace-left=['<Alt>a']
# switch-to-workspace-right=['<Alt>s']

[desktop/wm/keybindings]
switch-applications=@as []
switch-applications-backward=@as []
switch-windows=@as []
switch-windows-backward=@as []
move-to-workspace-left=@as []
move-to-workspace-down=@as []
move-to-workspace-up=@as []
move-to-workspace-right=@as []
switch-to-workspace-left=@as []
switch-to-workspace-right=@as []
; switch-to-workspace-down=['<Alt>j']
; switch-to-workspace-up=['<Alt>k']

[desktop/peripherals/touchpad]
speed=-1.5

[desktop/peripherals/keyboard]
repeat=true
delay=100
repeat-interval=50

[desktop/interface]
enable-animations=false

[shell/extensions/paperwm/keybindings]
switch-left=['<Alt>a']
switch-down=@as []
switch-up=@as []
switch-right=['<Alt>s']
move-left=['<Shift><Alt>a']
move-down=['<Shift><Alt>j']
move-up=['<Shift><Alt>k']
move-right=['<Shift><Alt>s']

switch-up-workspace=['<Alt>k']
switch-down-workspace=['<Alt>j']

toggle-scratch-window=['<Alt>t']
toggle-scratch=['<Shift><Alt>t']
toggle-maximize-width=['<Alt>f']
close-window=['<Alt>q']
cycle-width=['<Alt>r']

[shell/extensions/paperwm]
selection-border-size=4
selection-border-radius-top=8
selection-border-radius-bottom=4
animation-time=0.0
# swipe-sensitivity=[x, y]
#   値を小さくすると鈍くなる / 大きくすると敏感になる
#   例: かなり鈍く [1.2, 1.2], デフォルト [2.0, 2.0]
# swipe-friction=[x, y]
#   値を大きくすると止まりやすくなる（慣性が減る）
#   例: しっかり止めたい [0.5, 0.2], デフォルト [0.3, 0.1]
swipe-sensitivity=[8, 8]
swipe-friction=[0.3, 0.15]

[shell/keybindings]
toggle-application-view=@as []
toggle-overview=['<Control>space']

[settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']
terminal=@as []

[settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Alt>Return'
command='/home/mei/.local/kitty.app/bin/kitty'
name='Launch kitty'
