# Personal Zsh configuration file. It is strongly recommended to keep all
# shell customization and configuration (including exported environment
# variables such as PATH) in this file or in files sourced from it.
#
# Documentation: https://github.com/romkatv/zsh4humans/blob/v5/README.md.


# Periodic auto-update on Zsh startup: 'ask' or 'no'.
# You can manually run `z4h update` to update everything.
zstyle ':z4h:' auto-update      'no'
# Ask whether to auto-update this often; has no effect if auto-update is 'no'.
zstyle ':z4h:' auto-update-days '28'

# Keyboard type: 'mac' or 'pc'.
zstyle ':z4h:bindkey' keyboard  'mac'

# Don't start tmux.
zstyle ':z4h:' start-tmux       no

# Mark up shell's output with semantic information.
zstyle ':z4h:' term-shell-integration 'yes'

# Right-arrow key accepts one character ('partial-accept') from
# command autosuggestions or the whole thing ('accept')?
zstyle ':z4h:autosuggestions' forward-char 'accept'

# Recursively traverse directories when TAB-completing files.
zstyle ':z4h:fzf-complete' recurse-dirs 'yes'

# Enable direnv to automatically source .envrc files.
zstyle ':z4h:direnv'         enable 'yes'
# Show "loading" and "unloading" notifications from direnv.
zstyle ':z4h:direnv:success' notify 'yes'

# SSH when connecting to these hosts.
zstyle ':z4h:ssh:example-hostname1'   enable 'yes'
zstyle ':z4h:ssh:*.example-hostname2' enable 'no'
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*'                   enable 'no'

# Send these files over to the remote host when connecting over SSH to the
# enabled hosts.
zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh'

# Instruct zsh4humans to use fzf from PATH.
zstyle ':z4h:*' fzf-command fzf

# Clone additional Git repositories from GitHub.
#
# This doesn't do anything apart from cloning the repository and keeping it
# up-to-date. Cloned files can be used after `z4h init`. This is just an
# example. If you don't plan to use Oh My Zsh, delete this line.
z4h install ohmyzsh/ohmyzsh || return



function z4h-postinstall:replace-with-github-clone() {
  [[ -n $Z4H_PACKAGE_DIR && -n $Z4H_PACKAGE_NAME ]] && 'command' -v git 1>/dev/null || return 1

  'command' 'rm' -rf $Z4H_PACKAGE_DIR

  'command' 'git' clone --recurse-submodules --single-branch --depth 1 https://github.com/$Z4H_PACKAGE_NAME $Z4H_PACKAGE_DIR
}
# z4h install olets/zsh-abbr || return
# zstyle :z4h:olets/zsh-abbr postinstall z4h-postinstall:replace-with-github-clone || return

local plugins=(
  jeffreytse/zsh-vi-mode/vi-mode.plugin.zsh
  mfaerevaag/wd/wd.plugin.zsh
  momo-lab/zsh-abbrev-alias/abbrev-alias.plugin.zsh
  zuxfoucault/colored-man-pages_mod/colored-man-pages_mod.plugin.zsh
  hlissner/zsh-autopair/autopair.zsh
  # larkery/zsh-histdb/zsh-histdb.plugin.zsh
  Dbz/kube-aliases/kube-aliases.plugin.zsh
  wintermi/zsh-brew/zsh-brew.plugin.zsh
  t413/zsh-background-notify/bgnotify.plugin.zsh
  jimhester/per-directory-history/per-directory-history.plugin.zsh
  egyptianbman/zsh-git-worktrees/zsh-git-worktrees.zsh
)

# util for z4h install
extract_repo() {
  local fullpath=$1
  echo "${fullpath%/*/*}/${fullpath#*/}" | cut -d'/' -f1,2
}

for p in $plugins; do
  repo=$(extract_repo "$p")
  z4h install "$repo"
done

# Install or update core components (fzf, zsh-autosuggestions, etc.) and
# initialize Zsh. After this point console I/O is unavailable until Zsh
# is fully initialized. Everything that requires user interaction or can
# perform network I/O must be done above. Everything else is best done below.
z4h init || return

# https://github.com/romkatv/zsh4humans/blob/v5/tips.md#vi-mode
bindkey -v
bindkey "^I" z4h-fzf-complete

bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^R' z4h-fzf-history
bindkey '^L' z4h-clear-screen-soft-bottom
# command mode
bindkey -M vicmd '^A' beginning-of-line
bindkey -M vicmd '^E' end-of-line
bindkey -M vicmd '^R' z4h-fzf-history
bindkey -M vicmd '^O' z4h-cd-back
bindkey -M vicmd '^I' z4h-cd-forward
bindkey -M vicmd '^L' z4h-clear-screen-soft-bottom

bindkey "^?" backward-delete-char

# 'home' and 'end' keys
bindkey '^[[H' beginning-of-line
bindkey '^[[F' end-of-line
bindkey -M vicmd '^[[H' beginning-of-line
bindkey -M vicmd '^[[F' end-of-line
# Extend PATH.
path=(~/bin $path)

# Export environment variables.
export GPG_TTY=$TTY

# Source additional local files if they exist.
z4h source ~/.env.zsh

# Use additional Git repositories pulled in with `z4h install`.
for p in $plugins; do
  z4h source $p
done

export PER_DIRECTORY_HISTORY_TOGGLE='^V'

# Define key bindings.
z4h bindkey undo Ctrl+/   Shift+Tab  # undo the last command line change
z4h bindkey redo Option+/            # redo the last undone command line change

z4h bindkey z4h-cd-back    Shift+Left   # cd into the previous directory
z4h bindkey z4h-cd-forward Shift+Right  # cd into the next directory
z4h bindkey z4h-cd-up      Shift+Up     # cd into the parent directory
z4h bindkey z4h-cd-down    Shift+Down   # cd into a child directory

# Autoload functions.
autoload -Uz zmv


# Define named directories: ~w <=> Windows home directory on WSL.
[[ -z $z4h_win_home ]] || hash -d w=$z4h_win_home



alias clear=z4h-clear-screen-soft-bottom

eval "$(devbox global shellenv)"


source ~/.config/zsh/z4h/alias.zsh
source ~/.config/zsh/z4h/plugins.zsh

source ~/dotfiles/zsh/tmux-rename.zsh

source ~/dotfiles/shell/alias.sh
source ~/dotfiles/shell/envsetup.sh


export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

alias k='kubecolor'
alias kubectl='kubecolor'
source <(kubectl completion zsh);compdef kubecolor="kubectl"
source <(devbox completion zsh)
fpath=($(devbox global path)/.devbox/nix/profile/default-6-link/share/zsh/site-functions $fpath)


# homebrew completion
autoload -Uz compinit
compinit


# Set shell options: http://zsh.sourceforge.net/Doc/Release/Options.html.
setopt glob_dots     # no special treatment for file names with a leading dot
setopt no_auto_menu  # require an extra TAB press to open the completion menu
